# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: "monthly"
    cooldown:
      default-days: 14
    groups:
      all:
        patterns:
          - "*"
    target-branch: master
  - package-ecosystem: docker
    directories:
      - /
      - /contrib
    schedule:
      interval: "monthly"
    groups:
      all:
        patterns:
          - "*"
    target-branch: master
  - package-ecosystem: gomod
    directory: / # Location of package manifests
    schedule:
      interval: "cron"
      cronjob: "0 0 1-7,15-21 * 1" # at 00:00 on the 1st and 3rd Monday of each month
    cooldown:
      default-days: 3
    groups:
      vuls:
        patterns:
          - "github.com/MaineK00n/vuls-data-update"
          - "github.com/MaineK00n/vuls2"
          - "github.com/vulsio/go-cti"
          - "github.com/vulsio/go-cve-dictionary"
          - "github.com/vulsio/go-exploitdb"
          - "github.com/vulsio/go-kev"
          - "github.com/vulsio/go-msfdb"
          - "github.com/vulsio/gost"
          - "github.com/vulsio/goval-dictionary"
      trivy:
        patterns:
          - "github.com/aquasecurity/trivy"
          - "github.com/aquasecurity/trivy-db"
          - "github.com/aquasecurity/trivy-java-db"
      others:
        patterns:
          - "*"
        exclude-patterns:
          - "github.com/MaineK00n/vuls-data-update"
          - "github.com/MaineK00n/vuls2"
          - "github.com/vulsio/go-cti"
          - "github.com/vulsio/go-cve-dictionary"
          - "github.com/vulsio/go-exploitdb"
          - "github.com/vulsio/go-kev"
          - "github.com/vulsio/go-msfdb"
          - "github.com/vulsio/gost"
          - "github.com/vulsio/goval-dictionary"
          - "github.com/aquasecurity/trivy"
          - "github.com/aquasecurity/trivy-db"
          - "github.com/aquasecurity/trivy-java-db"
    target-branch: master
