# Gopkg.toml example
#
# Refer to https://golang.github.io/dep/docs/Gopkg.toml.html
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#   name = "github.com/x/y"
#   version = "2.4.0"
#
# [prune]
#   non-go = false
#   go-tests = true
#   unused-packages = true


[[constraint]]
  name = "github.com/Azure/azure-sdk-for-go"
  version = "15.1.0"

[[constraint]]
  name = "github.com/BurntSushi/toml"
  version = "0.3.0"

[[constraint]]
  name = "github.com/asaskevich/govalidator"
  version = "9.0.0"

[[constraint]]
  name = "github.com/aws/aws-sdk-go"
  version = "1.13.31"

[[constraint]]
  name = "github.com/boltdb/bolt"
  version = "1.3.1"

[[constraint]]
  name = "github.com/cenkalti/backoff"
  version = "2.0.0"

[[constraint]]
  branch = "master"
  name = "github.com/google/subcommands"

[[constraint]]
  branch = "master"
  name = "github.com/gosuri/uitable"

[[constraint]]
  branch = "master"
  name = "github.com/hashicorp/uuid"

[[constraint]]
  branch = "master"
  name = "github.com/howeyc/gopass"

[[constraint]]
  name = "github.com/jroimartin/gocui"
  version = "0.3.0"

[[constraint]]
  name = "github.com/k0kubun/pp"
  version = "2.3.0"

[[constraint]]
  branch = "master"
  name = "github.com/knqyf263/go-deb-version"

[[constraint]]
  branch = "master"
  name = "github.com/knqyf263/go-rpm-version"

[[constraint]]
  branch = "unfixed-cves"
  name = "github.com/knqyf263/gost"

[[constraint]]
  branch = "nvd-json"
  name = "github.com/kotakanbe/go-cve-dictionary"

[[constraint]]
  name = "github.com/kotakanbe/go-pingscanner"
  version = "0.1.0"

[[constraint]]
  branch = "master"
  name = "github.com/kotakanbe/goval-dictionary"

[[constraint]]
  branch = "master"
  name = "github.com/kotakanbe/logrus-prefixed-formatter"

[[constraint]]
  branch = "master"
  name = "github.com/mitchellh/go-homedir"

[[constraint]]
  name = "github.com/nlopes/slack"
  version = "0.2.0"

[[constraint]]
  name = "github.com/parnurzeal/gorequest"
  version = "0.2.15"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.0"

[[constraint]]
  name = "github.com/rifflock/lfshook"
  version = "2.3.0"

[[constraint]]
  branch = "master"
  name = "github.com/sirupsen/logrus"

[[constraint]]
  branch = "master"
  name = "golang.org/x/crypto"

[prune]
  go-tests = true
  unused-packages = true
