[cveDict]
Type = "redis"
Url = "redis://127.0.0.1/3"

[ovalDict]
  Type = "redis"
  Url = "redis://127.0.0.1/1"

[gost]
  Type = "redis"
  Url = "redis://127.0.0.1/2"

[exploit]
  Type = "redis"
  Url = "redis://127.0.0.1/4"

[metasploit]
  Type = "redis"
  Url = "redis://127.0.0.1/5"

[default]

[servers]

[servers.nvd_exact]
type = "pseudo"
cpeNames = [ "cpe:/a:rubyonrails:rails:3.0.1" ]
#cpeNames = [ "cpe:/a:rubyonrails:rails:4.0.0" ]

[servers.nvd_rough]
type = "pseudo"
cpeNames = [ "cpe:/a:openssl:openssl:1.1.1" ]

[servers.nvd_vendor_product]
 type = "pseudo"
 cpeNames = [ "cpe:/a:djangoproject:django" ]

[servers.nvd_match_no_jvn]
type = "pseudo"
cpeNames = [ "cpe:/a:apache:tomcat:7.0.27" ]

[servers.jvn_vendor_product]
type = "pseudo"
cpeNames = [ "cpe:/a:hitachi_abb_power_grids:afs660:1.0.0" ]

[servers.jvn_vendor_product_nover]
type = "pseudo"
cpeNames = [ "cpe:/o:nec:aterm_wg2600hp2_firmware"]

[servers.bundler]
type = "pseudo"
lockfiles = ["./integration/data/lockfile/Gemfile.lock"]

[servers.pip]
type = "pseudo"
lockfiles = ["./integration/data/lockfile/requirements.txt"]

[servers.pipenv]
type = "pseudo"
lockfiles = ["./integration/data/lockfile/Pipfile.lock"]

[servers.poetry]
type = "pseudo"
lockfiles = ["./integration/data/lockfile/poetry.lock"]

[servers.composer]
type = "pseudo"
lockfiles = ["./integration/data/lockfile/composer.lock"]

[servers.npm]
type = "pseudo"
lockfiles = ["./integration/data/lockfile/package-lock.json"]

[servers.yarn]
type = "pseudo"
lockfiles = ["./integration/data/lockfile/yarn.lock"]

[servers.cargo]
type = "pseudo"
lockfiles = ["./integration/data/lockfile/Cargo.lock"]

[servers.gomod]
type = "pseudo"
lockfiles = ["./integration/data/lockfile/go.sum"]

[servers.gobinary]
type = "pseudo"
lockfiles = ["./integration/data/lockfile/gobinary"]

[servers.jar]
type = "pseudo"
lockfiles = ["./integration/data/lockfile/test.jar"]

[servers.pom]
type = "pseudo"
lockfiles = ["./integration/data/lockfile/pom.xml"]

[servers.nuget-lock]
type = "pseudo"
lockfiles = ["./integration/data/lockfile/packages.lock.json"]

[servers.nuget-config]
type = "pseudo"
lockfiles = ["./integration/data/lockfile/packages.config"]

